# Generated by Django 3.1.1 on 2020-09-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(max_length=100)),
                ('song_artist', models.CharField(max_length=100)),
                ('song_album', models.CharField(max_length=100)),
                ('song_url', models.CharField(max_length=100)),
                ('song_file', models.FileField(default=None, upload_to='music/mp3')),
            ],
        ),
    ]
