# Generated by Django 3.1.1 on 2020-09-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_album',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_artist',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_url',
            field=models.CharField(max_length=100),
        ),
    ]
